<a href="https://colab.research.google.com/github/devyanic11/Deep-Learning/blob/main/backpropogation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame([[8,8,4], [7,9,5], [6,10,6], [5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [4]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [41]:
def initialize_parameters(layer_dims):
  #This will create no. of weights and biases according to the layer dimension
  #given as parameters
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):
    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))

  return parameters

In [42]:
def linear_forward(A_prev, W, b):
  Z = np.dot(W.T, A_prev)+b
  return Z

In [75]:
#Forward Propogation
def L_layer_forward(X, parameters):
  A = X
  L = len(parameters) // 2                #no. of layers in Neural Network

  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)

  return A, A_prev

In [47]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)    #Shape(no of features, no of training examples)
y = df[["lpa"]].values[0][0]

In [55]:
parameters = initialize_parameters([2,2,1])
y_hat, A1 = L_layer_forward(X, parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [49]:
def update_parameters(parameters, y, y_hat, A1, X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y-y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y-y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y-y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y-y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y-y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y-y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y-y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y-y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y-y_hat)*parameters['W2'][1][0])


In [52]:
(y - 0.32)**2

In [58]:
y_hat=y_hat[0][0]

In [64]:
update_parameters(parameters, y, y_hat, A1, X)

In [65]:
parameters

{'W1': array([[0.10753323, 0.10968558],
        [0.10753323, 0.10968558]]),
 'b1': array([[0.11605218],
        [0.00107618]]),
 'W2': array([[0.114976],
        [0.114976]]),
 'b2': array([[0.124336]])}

In [66]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1)    #Shape(no of features, no of training examples)
y = df[["lpa"]].values[1][0]

y_hat, A1 = L_layer_forward(X, parameters)

A0:  [[7]
 [9]]
W1:  [[0.10753323 0.10968558]
 [0.10753323 0.10968558]]
b1:  [[0.11605218]
 [0.00107618]]
----------------------------------------
A1:  [[1.83658382]
 [1.75604543]]
****************************************
A1:  [[1.83658382]
 [1.75604543]]
W2:  [[0.114976]
 [0.114976]]
b2:  [[0.124336]]
----------------------------------------
A2:  [[0.53740214]]
****************************************


In [67]:
update_parameters(parameters, y, y_hat, A1, X)

In [68]:
parameters

{'W1': array([[0.11574062, 0.12023793],
        [0.11569571, 0.12018019]]),
 'b1': array([[0.13254035],
        [0.00224224]]),
 'W2': array([[0.13136787],
        [0.13064905]]),
 'b2': array([[0.13957424]])}

In [76]:
# Epochs Implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):
  Loss = []

  for j in range(df.shape[0]):
    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1)
    y = df[['lpa']].values[j][0]

    y_hat, A1 = L_layer_forward(X, parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters, y, y_hat, A1, X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ', i+1, 'Loss - ', np.array(Loss).mean())

parameters

Epoch -  1 Loss -  25.1639490957267
Epoch -  2 Loss -  17.865635116306052
Epoch -  3 Loss -  8.91061986469564
Epoch -  4 Loss -  2.9738306798886227
Epoch -  5 Loss -  1.3184147473712438


{'W1': array([[0.26468114, 0.38658519],
        [0.27047028, 0.3979268 ]]),
 'b1': array([[0.4265299],
        [0.0285536]]),
 'W2': array([[0.42509061],
        [0.46967566]]),
 'b2': array([[0.4730615]])}

###Implementing the same in Keras

In [77]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [78]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim = 2))
model.add(Dense(1, activation='linear'))

In [79]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [80]:
model.get_weights()

[array([[-1.2197026 , -0.24435014],
        [-0.90723807,  1.0989827 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.47714913],
        [-0.23370159]], dtype=float32),
 array([0.], dtype=float32)]

In [81]:
new_weights = [np.array([[0.1,0.1], [0.1, 0.1]], dtype=np.float32), np.array([0.,0.], dtype=np.float32), np.array([[0.1],[0.1]], dtype=np.float32), np.array([0.], dtype=np.float32)]

In [82]:
model.set_weights(new_weights)

In [83]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [84]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [87]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 5ms/step - loss: 27.8783
Epoch 2/75
4/4 [==============================] - 0s 4ms/step - loss: 27.5861
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 27.2543
Epoch 4/75
4/4 [==============================] - 0s 4ms/step - loss: 26.9168
Epoch 5/75
4/4 [==============================] - 0s 5ms/step - loss: 26.5685
Epoch 6/75
4/4 [==============================] - 0s 4ms/step - loss: 26.1950
Epoch 7/75
4/4 [==============================] - 0s 3ms/step - loss: 25.8292
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 25.4496
Epoch 9/75
4/4 [==============================] - 0s 4ms/step - loss: 25.0608
Epoch 10/75
4/4 [==============================] - 0s 4ms/step - loss: 24.6466
Epoch 11/75
4/4 [==============================] - 0s 4ms/step - loss: 24.2393
Epoch 12/75
4/4 [==============================] - 0s 4ms/step - loss: 23.8440
Epoch 13/75
4/4 [==============================] - 0s 4ms/ste

<p>check classification code</p>